- name: Add ASR rules
  hosts: all
  tasks:
    - name: Add ASR rule 001
      win_shell: Add-MpPreference -AttackSurfaceReductionRules_Ids D1E49AAC-8F56-4280-B9BA-993A6D77406C -AttackSurfaceReductionRules_Actions Enabled

    - name: Add ASR rule 2
      win_shell: Add-MpPreference -AttackSurfaceReductionRules_Ids d1e49aac-8f56-4280-b9ba-993a6d77406c -AttackSurfaceReductionRules_Actions enable
