# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'


- name: "Install Wazuh Agent"
  hosts: all:!goad-ansible
  tasks:
    - name: "Download and Install Wazuh Agent"
      win_shell: |
        Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.2-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.11.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.11.msi /q WAZUH_MANAGER='192.168.56.100' WAZUH_REGISTRATION_SERVER='192.168.56.100'

    - name: "Start Wazuh Service"
      win_shell: NET START WazuhSvc
