# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'


- name: "Install Wazuh Agent"
  hosts: elk_log
  tasks:
    - name: "Download and Install Wazuh Agent"
      win_shell: |
        Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.3-1.msi -OutFile ${env:tmp}\wazuh-agent-4.7.3.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.7.3.msi /q WAZUH_MANAGER='{{ hostvars["wazuh"]["ansible_host"] }}' WAZUH_REGISTRATION_SERVER='{{ hostvars["wazuh"]["ansible_host"] }}'

    - name: "Start Wazuh Service"
      win_shell: NET START WazuhSvc
